### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by chrisc06** [springmusk026/ImGui-Unity-With-Layout#1]
skidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskidskid

**Comment by ToshiroZ** [comment]
This time he can skid since I open sourced mine
However the only thing similar now is the fact that eglSwapBuffers is used to draw

**Comment by ToshiroZ** [comment]
Which isn't unique to only me
Other people on PC also use it to draw imgui on OpenGL games

**Comment by chrisc06** [comment]
fair enough
