### ISSUE TITLE
Touch questions about the game

### ISSUE THREAD

**Issue by bflhjn1220** [springmusk026/ImGui-Unity-With-Layout#2]
You get the function with two offsets of unity and then do the api operation Xy, right?
I saw your algorithm through the source code because unity already has an operation, but I wonder if you don't apply hooks alone just calling can you? I have no test, I want to know, for cod this mobile game is feasible?
![image](https://user-images.githubusercontent.com/92655383/180633514-e5a58081-9ca4-4d16-914a-8d3a439559d7.png)
My telegraph number @vaselr1

**Comment by springmusk026** [comment]
check the latest update it will work for any app on android system

**Comment by bflhjn1220** [comment]
ok
